### ISSUE TITLE
Add filters on dashboard pangolin graph

### ISSUE THREAD

**Issue by elevu** [Fattigman/docker-sc2reporter#69]
Blocked by https://github.com/genomic-medicine-sweden/docker-sc2reporter/issues/68

**Comment by moedarrah** [comment]
https://34.125.210.143/docs#/Dashboard/get_dashboard_data_dashboard__get

**Comment by moedarrah** [comment]
create the filter checkboxes dynamically from the response
<img width="270" alt="Screenshot 2022-11-15 at 11 23 09" src="https://user-images.githubusercontent.com/41540288/201895374-c1c162c8-a7a7-4ceb-b7a4-25a262c3a5d4.png">

**Comment by moedarrah** [comment]
Blocked by: https://github.com/genomic-medicine-sweden/docker-sc2reporter/issues/86

**Comment by Fattigman** [comment]
Seems that fastapi encodes its requests in a weird way:
![Screenshot 2022-11-29 at 14 37 47](https://user-images.githubusercontent.com/32386766/204543490-4c4cd1c3-c593-4ff9-a840-109fbcb37a7f.png)

**Comment by Fattigman** [comment]
So the problem is that there are three different encodings:

1. Övrigt : UTF-8, what we can read and so forth
2. &Ouml;vrigt : HTML entity encoding, as Ö is a special character it's encoded as it is. It's the same for the other umlauts.
3. %26Ouml%3Bvrigt : URL encoding, as the character "&" and ";" have specific functions when passed through the url they will need to also be encoded.

This could have been avoided if we would have english language in our database and thus an issue has been created for it #134 , but until then these API calls will need to pass a url parser.

**Comment by moedarrah** [comment]
Done: https://github.com/genomic-medicine-sweden/docker-sc2reporter/pull/137
