### ISSUE TITLE
Dashboard - Decoded items do not work when filtered

### ISSUE THREAD

**Issue by moedarrah** [Fattigman/docker-sc2reporter#86]
Even when decoding the selection_criterions in the front-end I can't filter using (Övrigt - Allmän övervakning)

**Comment by Fattigman** [comment]
Copying my answer from #69 

So the problem is that there are three different encodings:

Övrigt : UTF-8, what we can read and so forth
Övrigt : HTML entity encoding, as Ö is a special character it's encoded as it is. It's the same for the other umlauts.
%26Ouml%3Bvrigt : URL encoding, as the character "&" and ";" have specific functions when passed through the url they will need to also be encoded.
