### ISSUE TITLE
The backend is redirecting calls by adding /api even if /api is included in the url

### ISSUE THREAD

**Issue by elevu** [Fattigman/docker-sc2reporter#97]
For example https://34.125.210.143/api/samples becomes https://34.125.210.143/api/api/samples

**Comment by Fattigman** [comment]
That's a weird behavior, will look into it straight away

**Comment by Fattigman** [comment]
It was a bug in fastapi routing module. When no trailing slash is suplied in the url, it redirects the request to the same url with doubled prefixes. https://34.125.210.143/api/samples/ would work fine but https://34.125.210.143/api/samples would not. 

I have however fixed this bug now by modifying the routing module so that it adds a trailing slashes when none i provided in the url.
